### ISSUE TITLE
Definition of trusted_range

### ISSUE THREAD

**Issue by dagewa** [cctbx/dxtbx#182]
What is the definition of `trusted_range`?

The name suggests an inclusive range [min_trusted_value, max_trusted_value], however many dxtbx format classes actually pass something like `trusted_range = (underload, overload)`. That is, the range is defined using the first _untrusted_ values at the edge. In addition to being confusing, this is problematic for data that is stored using a floating point type.

The code appears inconsistent in its treatment of `trusted_range`. For example, `is_value_in_trusted_range` actually suggests the lower end of the range is _trusted_, and shouldn't be defined as `underload`
https://github.com/cctbx/dxtbx/blob/bbb9f7eb50340811f1a3b942fb0eb416fa0218c5/model/panel.h#L155-L158

meanwhile, in `apply_trusted_range_mask` the lower end of the range appears _untrusted_
https://github.com/cctbx/dxtbx/blob/bbb9f7eb50340811f1a3b942fb0eb416fa0218c5/model/panel.h#L382-L385

At the other end of the range, the program `dxtbx.overload` treats the upper end as the highest _trusted_ value, not the overload value. There is also the program `dxtbx.saturation`, but I can't tell from a glance what this does and it is undocumented and free of comments.

As far as I can tell, the definition of `trusted_range` is not documented anywhere.

**Comment by graeme-winter** [comment]
Valid question: I suspect that the only reason why this has not been a _problem_ per se is we usually have a mask which is defined by a format class, and this is where the pixels are invalidated (in general) 

However I think defining this strictly, then ensuring it is applied consistently would be a good thing. 

I'll hold off for a moment on any opinions on what _correct_ should look like...

**Comment by graeme-winter** [comment]
Assert correct values for trusted range should be:

`trusted_range = (minimum_good, maximum_good)`

inclusive i.e. 

`good = (pixels >= trusted[0]) & (pixels <= trusted[1])`

I note that this is distinct from how it is _currently_ used i.e. in place of `underload, overload` we have `underload + 1, overload - 1` - assuming 1 is a sensible quantum

**Comment by graeme-winter** [comment]
Datum:

for full CBF images we interpret as 

```
            underload = find_undefined_value(cbf_handle)
            overload = cbf_handle.get_overload(0)
            trusted = (underload, overload)
```

**Comment by graeme-winter** [comment]
FWIW I have just looked through like two dozen format classes, and the consensus seems to be that the `trusted_range` is _exclusive_ i.e. it's usually assigned as `trusted_range=(underload,overload)`

**Comment by graeme-winter** [comment]
@dagewa asked yesterday on a related topic "does the trusted range apply to raw or corrected images? what about the gain?"

I believe that this is pertinent here.

**Comment by dagewa** [comment]
> Assert correct values for trusted range should be:
> 
> `trusted_range = (minimum_good, maximum_good)`
> 
> inclusive i.e.
> 
> `good = (pixels >= trusted[0]) & (pixels <= trusted[1])`

Assuming we have agreement on this, then this is just a _doing job_.

- [ ] Fix all `Format` classes to adhere to this definition.
- [ ] Fix `is_value_in_trusted_range`.
- [ ] Fix `apply_trusted_range_mask`.
- [ ] Fix `dxtbx.overload`.
- [ ] Look for effects in other areas of dxtbx / DIALS
- [ ] Figure out the purpose of `dxtbx.saturation` and fix if necessary, plus document.
- [ ] Document `trusted_range`, including answers to questions above such as "does the trusted range apply to raw or corrected images?"

**Comment by phyy-nx** [comment]
👍

**Comment by ndevenish** [comment]
I have run into this issue again, in the context of Nexus NXmx files. The NXmx definition [defines](https://manual.nexusformat.org/classes/applications/NXmx.html#index-42) inclusive trusted range of (minimum_good, maximum_good). We currently pass this to dxtbx as trusted_range = (minimum_good-1, maximum_good):

https://github.com/cctbx/dxtbx/blob/e4bc7c4965cfbb7e43df46e9ddea56a2bbb27119/src/dxtbx/nexus/__init__.py#L274-L281

However, as discussed above, except for `dxtbx.overload`, the upper range is consistently treated as `good = value < trusted_range[1]`. This means that we're incorrectly applying the meaning of the NXmx field.

Fixing this... also has another potential problem. Both `.nxs` files in dials-data have `saturation_value = 65535` - by the nexus definition, this is basically useless because it implies that there is _no_ 16-bit cut-off value (however the data in these nonetheless uses 65535 as a mask value - only one of them has a separate pixel mask, so to strictly follow the definition the other should not have the modules masked).

Does this imply that there are "in the wild" NXmx datasets that we've written, relying on an incorrect definition for these? the only way I can see to resolve this is to:
- Write the trusted_range upper limit as Nexus (saturation_value + 1)
- ... unless it's equal to INT_MAX for the data set in which case write it as saturation_value

**Comment by dagewa** [comment]
The `trusted_range` is now defined as the inclusive range [min-valid-value, max-valid-value]
