### ISSUE TITLE
Misreading trusted range for Eiger data collected with DECTRIS file writer

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#585]
to_xds(foo.imageset).get_detector()[0].get_trusted_range(), I get a tuple back. tuple[1] is correct, but tuple[0] is -2147483647.0, or -(2^31-1). It should be zero

Breaks `fast_dp` amongst other things

**Comment by graeme-winter** [comment]
Also: while we are there the detector is reading as _upstream_ of the sample with the current state of `main` - something which I recall fixing

**Comment by graeme-winter** [comment]
Yup:

https://github.com/cctbx/dxtbx/pull/550

**Comment by rjgildea** [comment]
Looking at proper NXmx fixes for this and #585 in https://github.com/cctbx/dxtbx/tree/dectris-filewriter-nxmx

**Comment by dagewa** [comment]
Being caught by this
https://github.com/cctbx/dxtbx/blob/50f850417b46548805d1baafab5cd7bade62ee71/src/dxtbx/format/nexus.py#L1008-L1021

**Comment by dagewa** [comment]
This behaviour comes from https://github.com/cctbx/dxtbx/pull/180

**Comment by rjgildea** [comment]
Yes, this is what [this line](https://github.com/cctbx/dxtbx/blob/e9f973576fbc38d658eef094a0a6debd1984ae59/src/dxtbx/format/FormatNXmxEigerFilewriter.py#L29-L30) is to catch. I think there are enough problems with the legacy `FormatNexus` (i.e. a simple reverting to that format class doesn't fix the issues with reading latest EIGER filewriter images) that we might as well try to fix the newer `FormatNXmx` to handle these images, rather than spending time backporting fixes to `FormatNexus`.

**Comment by dagewa** [comment]
Agreed, I'm very happy to leave this alone

**Comment by graeme-winter** [comment]
> Yes, this is what [this line](https://github.com/cctbx/dxtbx/blob/e9f973576fbc38d658eef094a0a6debd1984ae59/src/dxtbx/format/FormatNXmxEigerFilewriter.py#L29-L30) is to catch. I think there are enough problems with the legacy `FormatNexus` (i.e. a simple reverting to that format class doesn't fix the issues with reading latest EIGER filewriter images) that we might as well try to fix the newer `FormatNXmx` to handle these images, rather than spending time backporting fixes to `FormatNexus`.

Endorsed

I had some WIP for this for `FormatNXmx` but am not wedded to it. I would encourage a quick fix followed by a more cautious investigation.

**Comment by dagewa** [comment]
This was fixed by 2bffbcb.
